apiVersion: v1
appVersion: "0.1.0"
name: healenium
description: Healenium Helm chart for Kubernetes
version: 0.1.0
sources:
  - https://github.com/politico/infra-healenium-helm
keywords:
  - healenium
